# SPDX-FileCopyrightText: 2018 German Aerospace Center (DLR)
# SPDX-License-Identifier: MIT


check_code:
  image: python:3.8
  stage: test
  script:
    - cd code
    - ./test.sh
  tags:
    - docker
  artifacts:
    paths: ["code/*.png"]
